services:
  mongo:
    image: mongo:7.0
    container_name: mogi-mongo
    command: mongod --replSet rs0 --port 27017 --auth --keyFile /data/mongodb-keyfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mogi
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/mongodb-keyfile:/data/mongodb-keyfile
    networks:
      - mogi-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-setup:
    image: mongo:7.0
    container_name: mogi-mongo-setup
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./docker/mongo/setup.sh:/mongo-setup.sh
    command: sh /mongo-setup.sh
    networks:
      - mogi-network
    restart: on-failure

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.container-volumes/mongo/data

networks:
  mogi-network:
    driver: bridge
