name: mogi-dev

services:
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    container_name: mogi-dev-mongo
    command: mongod --config /etc/mongod.conf
    ports:
      - "27117:27117"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mogi
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mogi
    volumes:
      - mogi-dev-mongo-data:/data/db

  redis-stack:
    build:
      context: ./docker/redis-stack
      dockerfile: Dockerfile
    container_name: mogi-dev-redis-stack
    ports:
      - "6470:6379"
    volumes:
      - mogi-dev-redis-stack-data:/data
    environment:
      REDIS_ARGS: "--requirepass 1234"

volumes:
  mogi-dev-mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.container-volumes/mongo/data
  mogi-dev-redis-stack-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.container-volumes/redis-stack/data
