services:
  mongo:
    image: mongo:7.0
    container_name: mogi-mongo
    command: mongod --replSet rs0 --port 27117 --auth --keyFile /data/keyfile --bind_ip 0.0.0.0
    ports:
      - "27117:27117"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mogi
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mogi
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/keyfile:/data/keyfile
      - ./docker/mongo/setup.sh:/data/setup.sh

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.container-volumes/mongo/data
