services:
  mogi-mongo-dev:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    container_name: mogi-mongo-dev
    command: mongod --config /etc/mongod.conf
    ports:
      - "27117:27117"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mogi
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mogi
    volumes:
      - mogi-mongo-dev-data:/data/db

volumes:
  mogi-mongo-dev-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.container-volumes/mongo/data
