name: mogi-dev

services:
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    container_name: mogi-dev-mongo
    command: mongod --config /etc/mongod.conf
    ports:
      - "27117:27117"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mogi
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mogi
    volumes:
      - .container-volumes/mongo/data:/data/db

  redis-stack:
    build:
      context: ./docker/redis-stack
      dockerfile: Dockerfile
    container_name: mogi-dev-redis-stack
    ports:
      - "6479:6379"
    volumes:
      - .container-volumes/redis-stack/data:/data
    environment:
      REDIS_ARGS: "--requirepass 1234"
